# Generated by the ytcli release workflow. Edits here are overwritten.
class Ytcli < Formula
  desc "Yandex Tracker command-line client, sized for agents"
  homepage "https://github.com/ormeilu/yandex-tracker-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.1/ytcli-aarch64-apple-darwin.tar.gz"
      sha256 "dd69dfa0f97b4a7ad0110218c520efc81db5fbd6a680278fff8db4c0e69da217"
    end
    on_intel do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.1/ytcli-x86_64-apple-darwin.tar.gz"
      sha256 "1199d2c93c093ea5ed9f071b5a305ca7496313aca673800fb02ce93a983930a9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.1/ytcli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9e8caec66c746dfb913d60e5533a26306b2030a9dd3f1fe9493751f258bbc3cd"
    end
    on_intel do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.1/ytcli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7bc3e682514d4907805bea42fdb91e693a80450c31a9854aee0050f1513ff636"
    end
  end

  def install
    # The tarball has one top-level directory and Homebrew has already
    # stepped into it, so the binary is right here. Globbing for
    # `*/ytcli` finds nothing and fails inside Pathname.
    bin.install "ytcli"
    doc.install "README.md"
    generate_completions_from_executable(bin/"ytcli", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ytcli --version")
  end
end
