# Generated by the ytcli release workflow. Edits here are overwritten.
class Ytcli < Formula
  desc "Yandex Tracker command-line client, sized for agents"
  homepage "https://github.com/ormeilu/yandex-tracker-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.0/ytcli-aarch64-apple-darwin.tar.gz"
      sha256 "e8c8359947049afd04cf786362d5553ba60be21032191a01ae5e84feee508df9"
    end
    on_intel do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.0/ytcli-x86_64-apple-darwin.tar.gz"
      sha256 "a45213571c81277b00576974258909c22ac5d34373a91b20232aeae12186bf53"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.0/ytcli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bf6cfa56934f70854e3e78ecc6ee52deb924f3c9778489ff3eb544d62fc401b7"
    end
    on_intel do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.3.0/ytcli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "495711fd4476a270fddc2485a5e8a856782e7ce6069211647228bc308ec21994"
    end
  end

  def install
    # The tarball has one top-level directory and Homebrew has already
    # stepped into it, so the binary is right here. Globbing for
    # `*/ytcli` finds nothing and fails inside Pathname.
    bin.install "ytcli"
    doc.install "README.md"
    generate_completions_from_executable(bin/"ytcli", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ytcli --version")
  end
end
