# Generated by the ytcli release workflow. Edits here are overwritten.
class Ytcli < Formula
  desc "Yandex Tracker command-line client, sized for agents"
  homepage "https://github.com/ormeilu/yandex-tracker-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.5.2/ytcli-aarch64-apple-darwin.tar.gz"
      sha256 "b5e539bedb752a7730bf3ed4c3ef6b8a6084bb44edb1304039d21a33c34e4934"
    end
    on_intel do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.5.2/ytcli-x86_64-apple-darwin.tar.gz"
      sha256 "5e09ce5697732eff913db8db33b3bff62f61ff58e505b65b7393e757ee1b1dc7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.5.2/ytcli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "01b65dca08cc03f707000f6c3f63ef431218d493c9335a4058dad67359ff968b"
    end
    on_intel do
      url "https://github.com/ormeilu/yandex-tracker-cli/releases/download/v0.5.2/ytcli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b148c8684f2ed28311ca824e7381ec5510231a1477dd2b19f63211cc82766697"
    end
  end

  def install
    # The tarball has one top-level directory and Homebrew has already
    # stepped into it, so the binary is right here. Globbing for
    # `*/ytcli` finds nothing and fails inside Pathname.
    bin.install "ytcli"
    doc.install "README.md"
    generate_completions_from_executable(bin/"ytcli", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ytcli --version")
  end
end
